set -gq @thm_bg "{{ colors.surface.dark.hex | lighten: 4.5 }}"
set -gq @thm_fg "{{ colors.on_surface.dark.hex }}"
set -gq @thm_primary "{{ colors.primary.dark.hex }}"
set -gq @thm_secondary "{{ colors.secondary.dark.hex }}"
set -gq @thm_tertiary "{{ colors.tertiary.dark.hex }}"
set -gq @thm_red "{{ colors.error.default.hex }}"
set -gq @thm_gray "{{ colors.surface_variant.default.hex | lighten: 6 }}"
set -gq @thm_lines "{{ colors.outline_variant.default.hex }}"
set -gq @thm_selection "{{ colors.secondary_container.default.hex | lighten: -3.3 }}"
