# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0e2e8"

# Title color for boxes
theme[title]="#9ccbfb"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b9c8da"

# Background color of selected item in processes box
theme[selected_bg]="#9ccbfb"

# Foreground color of selected item in processes box
theme[selected_fg]="#003151"

# Color of inactive/disabled text
theme[inactive_fg]="#c2c7cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d4bfe6"

# Cpu box outline color
theme[cpu_box]="#8c9199"

# Memory/disks box outline color
theme[mem_box]="#8c9199"

# Net up/down box outline color
theme[net_box]="#8c9199"

# Processes box outline color
theme[proc_box]="#8c9199"

# Box divider line and small boxes line color
theme[div_line]="#4d5259"

# Temperature graph colors
theme[temp_start]="#b9c8da"
theme[temp_mid]="#9ccbfb"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b9c8da"
theme[cpu_mid]="#9ccbfb"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b9c8da"
theme[free_mid]=""
theme[free_end]="#455363"

# Mem/Disk cached meter
theme[cached_start]="#d4bfe6"
theme[cached_mid]=""
theme[cached_end]="#5b4b6c"

# Mem/Disk available meter
theme[available_start]="#9ccbfb"
theme[available_mid]=""
theme[available_end]="#21557f"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#a7060f"

# Download graph colors
theme[download_start]="#b9c8da"
theme[download_mid]="#9ccbfb"
theme[download_end]="#d4bfe6"

# Upload graph colors
theme[upload_start]="#b9c8da"
theme[upload_mid]="#9ccbfb"
theme[upload_end]="#d4bfe6"
