# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f0e5d8"

# Title color for boxes
theme[title]="#eac16c"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d8c4a0"

# Background color of selected item in processes box
theme[selected_bg]="#eac16c"

# Foreground color of selected item in processes box
theme[selected_fg]="#352500"

# Color of inactive/disabled text
theme[inactive_fg]="#d0c5b4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b1cfa9"

# Cpu box outline color
theme[cpu_box]="#9f9585"

# Memory/disks box outline color
theme[mem_box]="#9f9585"

# Net up/down box outline color
theme[net_box]="#9f9585"

# Processes box outline color
theme[proc_box]="#9f9585"

# Box divider line and small boxes line color
theme[div_line]="#6c6355"

# Temperature graph colors
theme[temp_start]="#d8c4a0"
theme[temp_mid]="#eac16c"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d8c4a0"
theme[cpu_mid]="#eac16c"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d8c4a0"
theme[free_mid]=""
theme[free_end]="#726245"

# Mem/Disk cached meter
theme[cached_start]="#b1cfa9"
theme[cached_mid]=""
theme[cached_end]="#506b4c"

# Mem/Disk available meter
theme[available_start]="#eac16c"
theme[available_mid]=""
theme[available_end]="#7f5f13"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#c32220"

# Download graph colors
theme[download_start]="#d8c4a0"
theme[download_mid]="#eac16c"
theme[download_end]="#b1cfa9"

# Upload graph colors
theme[upload_start]="#d8c4a0"
theme[upload_mid]="#eac16c"
theme[upload_end]="#b1cfa9"
