# Matugen template for btop

theme[main_bg]=""

theme[main_fg]="#e1e2e8"
theme[title]="#9fcafc"
theme[hi_fg]="#bac8db"
theme[selected_bg]="#9fcafc"

# Foreground color of selected item in processes box
theme[selected_fg]="#003155"

# Color of inactive/disabled text
theme[inactive_fg]="#c3c7cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d6bee5"

# Cpu box outline color
theme[cpu_box]="#465363"

# Memory/disks box outline color
theme[mem_box]="#465363"

# Net up/down box outline color
theme[net_box]="#465363"

# Processes box outline color
theme[proc_box]="#465363"

# Box divider line and small boxes line color
theme[div_line]="#4d5259"

# Temperature graph colors
theme[temp_start]="#bac8db"
theme[temp_mid]="#9fcafc"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#bac8db"
theme[cpu_mid]="#9fcafc"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#bac8db"
theme[free_mid]=""
theme[free_end]="#465363"

# Mem/Disk cached meter
theme[cached_start]="#d6bee5"
theme[cached_mid]=""
theme[cached_end]="#5d4b6b"

# Mem/Disk available meter
theme[available_start]="#9fcafc"
theme[available_mid]=""
theme[available_end]="#265480"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#a7060f"

# Download graph colors
theme[download_start]="#bac8db"
theme[download_mid]="#9fcafc"
theme[download_end]="#d6bee5"

# Upload graph colors
theme[upload_start]="#bac8db"
theme[upload_mid]="#9fcafc"
theme[upload_end]="#d6bee5"
