cursor            #92cef6
cursor_text_color #00324a

foreground            #dfe3e7
background            #192025
selection_foreground  #1f313d
selection_background  #b6c9d8
url_color             #b6c9d8

color0                #1a2126
color1                #f69292
color2                #c4f692
color3                #f6b792
color4                #92cef6
color5                #cdc0e9
color6                #b6c9d8
color7                #dfe3e7

color8                #586269
# color9                #f04b4b
# color10               #b0f36c
# color11                #f29763
# color12               #0c577a
# color13               #564d6f
color14               #425461
color15               #c1c7ce

color9                #f37171
color10                #c4f692
color11                #f5ad84
color12                #92cef6
color13                #cdc0e9

mark1_foreground #001e2e
mark1_background #c7e7ff
mark2_foreground #0b1d29
mark2_background #d2e5f5
mark3_foreground #322559
mark3_background #e8ddff

active_tab_foreground #00324a
active_tab_background #92cef6
inactive_tab_foreground #ffffff
inactive_tab_background #0c577a

active_border_color #92cef6
inactive_border_color #00324a

color255              #0c577a
color254              #92cef6
color253              #425461
color252              #b6c9d8
color251              #564d6f
color250              #cdc0e9
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #00324a
color234              #ffffff
color235              #1f313d
color236              #ffffff
color237              #322a4a
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #92cef6
color244              #ffb4ab
color245              #4c5358

