cursor            #dbc1b4
cursor_text_color #3b2b22

foreground            #e7e1df
background            #211e1d
selection_foreground  #352d29
selection_background  #d2c4bd
url_color             #d2c4bd

color0                #231f1e
color1                #cf9c9c
color2                #c8dbb4
color3                #d6baaa
color4                #dbc1b4
color5                #cdc6b0
color6                #d2c4bd
color7                #e7e1df

color8                #6a5e57
# color9                #c28080
# color10               #b3ce98
# color11                #caa692
# color12               #614e43
# color13               #565240
color14               #5a504b
color15               #d2c4bd

color9                #cf9c9c
color10                #c8dbb4
color11                #d6baaa
color12                #dbc1b4
color13                #cdc6b0

mark1_foreground #261910
mark1_background #f8ddcf
mark2_foreground #211a16
mark2_background #eee0d9
mark3_foreground #413c1e
mark3_background #e9e2cb

active_tab_foreground #3b2b22
active_tab_background #dbc1b4
inactive_tab_foreground #ffffff
inactive_tab_background #614e43

active_border_color #dbc1b4
inactive_border_color #3b2b22

color255              #614e43
color254              #dbc1b4
color253              #5a504b
color252              #d2c4bd
color251              #565240
color250              #cdc6b0
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #3b2b22
color234              #ffffff
color235              #352d29
color236              #ffffff
color237              #322f1f
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #dbc1b4
color244              #ffb4ab
color245              #5a504a

