background                #1d1d20
foreground                #deddda

selection_background      #3a3a3d
selection_foreground      #f6f5f4

url_color                 #b0afac

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #deddda
cursor_text_color         #1d1d20

active_border_color       #5a5a5d
inactive_border_color     #2a2a2d
bell_border_color         #f6f5f4
visual_bell_color         none

active_tab_background     #242424
active_tab_foreground     #fcfcfc
inactive_tab_background   #303030
inactive_tab_foreground   #b0afac
tab_bar_background        none
tab_bar_margin_color      none

color0                    #1d1d20
color1                    #4a4a4d
color2                    #5c5c5f
color3                    #6e6e71
color4                    #808083
color5                    #929295
color6                    #a4a4a7
color7                    #deddda

color8                    #9a9996
color9                    #b0afac
color10                   #c0bfbc
color11                   #d0cfcc
color12                   #e0dfdc
color13                   #eae9e6
color14                   #f2f1ee
color15                   #f6f5f4
