cursor            #ffb689
cursor_text_color #4f2200

foreground            #f0dfd7
background            #281d15
selection_foreground  #41291a
selection_background  #e5bfa9
url_color             #e5bfa9

color0                #2a1e16
color1                #ff6565
color2                #c4ff89
color3                #ffab7a
color4                #ffb689
color5                #cac993
color6                #e5bfa9
color7                #f0dfd7

color8                #6f5c52
# color9                #ff3d3d
# color10               #b0ff60
# color11                #ff9456
# color12               #7c431a
# color13               #545428
color14               #684c3b
color15               #d7c3b8

color9                #ff6565
color10                #c4ff89
color11                #ffab7a
color12                #ffb689
color13                #cac993

mark1_foreground #311300
mark1_background #ffdbc7
mark2_foreground #2b1709
mark2_background #ffdbc7
mark3_foreground #505000
mark3_background #e7e6ad

active_tab_foreground #4f2200
active_tab_background #ffb689
inactive_tab_foreground #ffffff
inactive_tab_background #7c431a

active_border_color #ffb689
inactive_border_color #4f2200

color255              #7c431a
color254              #ffb689
color253              #684c3b
color252              #e5bfa9
color251              #545428
color250              #cac993
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #4f2200
color234              #ffffff
color235              #41291a
color236              #ffffff
color237              #303108
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #ffb689
color244              #ffb4ab
color245              #5e4f46

