set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

set -g mouse on
set -g set-clipboard on

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file .tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8

thm_bg="#181825"      # base
thm_fg="#cdd6f4"      # text
thm_cyan="#89dceb"    # sky
thm_black="#181825"   # mantle
thm_gray="#45475a"    # surface1
thm_magenta="#cba6f7" # mauve
thm_pink="#f5c2e7"    # pink
thm_red="#f38ba8"     # red
thm_green="#a6e3a1"   # green
thm_yellow="#f9e2af"  # yellow
thm_blue="#89b4fa"    # blue
thm_orange="#fab387"  # peach
thm_black4="#585b70"  # surface2

 set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"

set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_pink}"

set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

set -g window-status-current-format "#[fg=${thm_gray},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_fg},bg=${thm_gray}] #I: #[fg=${thm_magenta},bg=${thm_gray}](✓) #[fg=${thm_cyan},bg=${thm_gray}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_magenta},bg=${thm_gray}]#[fg=${thm_gray},bg=${thm_bg}]"

set -g window-status-format "#[fg=${thm_bg},bg=${thm_bg}] #[fg=${thm_blue},bg=${thm_bg}]#I: #[fg=${thm_fg},bg=${thm_bg}]#W "

set -g status-right "#[fg=${thm_blue},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_blue},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_gray}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_gray}] #S "

set -g status-left ""

set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"
