return {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "nvim-telescope/telescope.nvim",
    { "ThePrimeagen/harpoon", branch = "harpoon2" },
    { "catppuccin/nvim", name = "catppuccin", priority = 1000 },

    "akinsho/bufferline.nvim",
    "nvim-lualine/lualine.nvim",
    "nvim-tree/nvim-tree.lua",
    "brenoprata10/nvim-highlight-colors",
    "tpope/vim-fugitive",
    "mbbill/undotree",
    "ojroques/vim-oscyank",
    "windwp/nvim-autopairs",
    "captbaritone/better-indent-support-for-php-with-html",
    { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
    "nvim-treesitter/nvim-treesitter-textobjects",
    "nvim-treesitter/nvim-treesitter-context",
}
