cursor            #84d2e5
cursor_text_color #00343d

foreground            #dee3e5
background            #182024
selection_foreground  #1b3238
selection_background  #b2cbd2
url_color             #b2cbd2

color0                #192225
color1                #df6767
color2                #b5e584
color3                #e29f77
color4                #84d2e5
color5                #bec5eb
color6                #b2cbd2
color7                #dee3e5

color8                #566367
# color9                #d84545
# color10               #a0de62
# color11                #dc8a5a
# color12               #005a69
# color13               #495070
color14               #3e565c
color15               #bfc8cb

color9                #df6767
color10                #b5e584
color11                #e29f77
color12                #84d2e5
color13                #bec5eb

mark1_foreground #001f25
mark1_background #a8edff
mark2_foreground #051f24
mark2_background #cde7ee
mark3_foreground #1f2c5d
mark3_background #dce1ff

active_tab_foreground #00343d
active_tab_background #84d2e5
inactive_tab_foreground #ffffff
inactive_tab_background #005a69

active_border_color #84d2e5
inactive_border_color #00343d

color255              #005a69
color254              #84d2e5
color253              #3e565c
color252              #b2cbd2
color251              #495070
color250              #bec5eb
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #00343d
color234              #ffffff
color235              #1b3238
color236              #ffffff
color237              #262d4b
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #84d2e5
color244              #ffb4ab
color245              #4a5356

