cursor            #9dcbfb
cursor_text_color #002a47

foreground            #e5e7ed
background            #090c10
selection_foreground  #1b2937
selection_background  #b9c8da
url_color             #b9c8da

#: black 000000 767676
color0  #101418
color8  #35393d
#: red cc0403 f2201f
color1  #447fb3
color9  #3d72a1
#: green 19cb00 23fd00
color2  #b9c8da
color10 #d5e4f7
#: yellow cecb00 fffd00
color3  #f9f5fb
color11 #f0dbff
#: blue 0d73cc 1a8fff
color4  #1974b5
color12 #9dcbfb
#: magenta cb1ed1 fd28ff
color5  #576d84
color13 #b9c8da
#: cyan 0dcdcd 14ffff
color6  #755e8d
color14 #d4bee6
#: white dddddd ffffff
color7  #edeef1
color15 #e5e7ed

mark1_foreground #001d34
mark1_background #cfe5ff
mark2_foreground #0e1d2a
mark2_background #d5e4f7
mark3_foreground #3c2457
mark3_background #f0dbff

active_tab_foreground #002a47
active_tab_background #9dcbfb
inactive_tab_foreground #ffffff
inactive_tab_background #386893

active_border_color #9dcbfb
inactive_border_color #002a47
# bell_border_color #ff5a00
