cursor            #bac3ff
cursor_text_color #202a5f

foreground            #e3e1e9
background            #1c1d25
selection_foreground  #2b2e40
selection_background  #c3c5dd
url_color             #c3c5dd

color0                #1d1f27
color1                #ffb4ab
color2                #e5bad8
color3                #c3c5dd
color4                #bac3ff
color5                #e5bad8
color6                #c3c5dd
color7                #e3e1e9

color8                #46464f
color9                #ffcbc5
color10               #694760
color11               #4e5165
color12               #444e85
color13               #434659
color14               #5d3c55
color15               #c6c5d0

mark1_foreground #0a154b
mark1_background #dee0ff
mark2_foreground #171a2c
mark2_background #dfe1f9
mark3_foreground #512148
mark3_background #ffd7f1

active_tab_foreground #202a5f
active_tab_background #bac3ff
inactive_tab_foreground #ffffff
inactive_tab_background #444e85

active_border_color #bac3ff
inactive_border_color #202a5f

color255              #444e85
color254              #bac3ff
color253              #4e5165
color252              #c3c5dd
color251              #694760
color250              #e5bad8
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #202a5f
color234              #ffffff
color235              #2b2e40
color236              #ffffff
color237              #42253c
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #bac3ff
color244              #ffb4ab
color245              #51515a

