cursor            #80d4dc
cursor_text_color #003539

foreground           #e0e2e8
background            #191f26
selection_foreground  #1a3335
selection_background  #b1cbce
url_color             #b1cbce

color0                #191f26
color1                #ffb4ab
color2                #C7F0BD
color3                #F4F1BB
color4                #9ccbfb
color5                #d4bfe6
color6                #80d4dc
color7                #e0e2e8

color8                #151d2e
color9                #ffffff
color10               #ffffff
color11               #d8ae97
color12               #ffffff
color13               #ffffff
color14               #ffffff
color15               #fff8f0

mark1_foreground #002022
mark1_background #9df0f8
mark2_foreground #051f21
mark2_background #cce8ea
mark3_foreground #123161
mark3_background #d7e2ff

active_tab_foreground #003539
active_tab_background #80d4dc
inactive_tab_foreground #ffffff
inactive_tab_background #005b61

active_border_color #80d4dc
inactive_border_color #003539
