cursor            #9fcafc
cursor_text_color #003155

foreground            #e1e2e8
background            #1a2127
selection_foreground  #23303f
selection_background  #bac8db
url_color             #bac8db

color0    #1a2127
color1    #f78181
color2    #a6d07b
color3    #faae80
color4    #9fcafc
color5    #d6bee5
color6    #63d4d4
color7    #e1e2e8

color8    #505961
color9    #f8aeae
color10   #bdd9a0
color11   #facbae
color12   #cde3fc
color13   #eae0f1
color14   #8adbdb
color15   #f3f3f5

mark1_foreground #001d35
mark1_background #d1e4ff
mark2_foreground #0f1c2b
mark2_background #d6e4f7
mark3_foreground #402356
mark3_background #f2daff

active_tab_foreground #003155
active_tab_background #9fcafc
inactive_tab_foreground #ffffff
inactive_tab_background #265480

active_border_color #9fcafc
inactive_border_color #003155
