set -gq @thm_bg "#191f26"
set -gq @thm_fg "#e0e2e8"
set -gq @thm_primary "#9ecafc"
set -gq @thm_secondary "#bac8db"
set -gq @thm_tertiary "#d5bee5"
set -gq @thm_red "#ffb4ab"
set -gq @thm_gray "#50565f"
set -gq @thm_lines "#4d5259"
set -gq @thm_selection "#3f4b59"
