set -gq @thm_bg "#192025"
set -gq @thm_fg "#dfe3e7"
set -gq @thm_primary "#92cef6"
set -gq @thm_secondary "#b6c9d8"
set -gq @thm_tertiary "#cdc0e9"
set -gq @thm_red "#ffb4ab"
set -gq @thm_gray "#4f585e"
set -gq @thm_lines "#4c5358"
set -gq @thm_selection "#3b4b57"
