set -gq @thm_bg "#211e1d"
set -gq @thm_fg "#e7e1df"
set -gq @thm_primary "#dbc1b4"
set -gq @thm_secondary "#d2c4bd"
set -gq @thm_tertiary "#cdc6b0"
set -gq @thm_red "#ffb4ab"
set -gq @thm_gray "#5f544e"
set -gq @thm_lines "#5a504a"
set -gq @thm_selection "#514843"
