set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

set -g mouse on
set -g set-clipboard on

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8

# Matugen color defaults
set -gq @thm_bg "#191f26"
set -gq @thm_fg "#e0e2e8"
set -gq @thm_primary "#9ecafc"
set -gq @thm_secondary "#bac8db"
set -gq @thm_tertiary "#d5bee5"
set -gq @thm_red "#ffb4ab"
set -gq @thm_gray "#50565f"
set -gq @thm_lines "#4d5259"
set -gq @thm_selection "#3f4b59"

# Source generated matugen colors
source-file ~/.config/tmux/tmux-colors.conf

set -gu status-bg
set -gu status-fg
set -g status "on"
set -g status-style "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

set -g message-style "fg=#{@thm_primary},bg=#{@thm_gray},align=centre"
set -g message-command-style "fg=#{@thm_primary},bg=#{@thm_gray},align=centre"

set -g pane-border-style "fg=#{@thm_lines}"
set -g pane-active-border-style "fg=#{@thm_primary}"

set -g window-status-activity-style "fg=#{@thm_fg},bg=#{@thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=#{@thm_fg},bg=#{@thm_bg},none"

set -g window-status-current-format "#[fg=#{@thm_gray},bg=#{@thm_bg},nobold,nounderscore,noitalics]#[fg=#{@thm_fg},bg=#{@thm_gray}] #I: #[fg=#{@thm_tertiary},bg=#{@thm_gray}](✓) #[fg=#{@thm_primary},bg=#{@thm_gray}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=#{@thm_tertiary},bg=#{@thm_gray}]#[fg=#{@thm_gray},bg=#{@thm_bg}]"

set -g window-status-format "#[fg=#{@thm_bg},bg=#{@thm_bg}] #[fg=#{@thm_secondary},bg=#{@thm_bg}]#I: #[fg=#{@thm_fg},bg=#{@thm_bg}]#W "

set -g status-right "#[fg=#{@thm_primary},bg=#{@thm_bg},nobold,nounderscore,noitalics]█#[fg=#{@thm_bg},bg=#{@thm_primary},nobold,nounderscore,noitalics] #[fg=#{@thm_fg},bg=#{@thm_gray}] #W #{?client_prefix,#[fg=#{@thm_tertiary}],#[fg=#{@thm_secondary}]}#[bg=#{@thm_gray}]█#{?client_prefix,#[bg=#{@thm_tertiary}],#[bg=#{@thm_secondary}]}#[fg=#{@thm_bg}] #[fg=#{@thm_fg},bg=#{@thm_gray}] #S "

set -g status-left ""

set -F -g clock-mode-colour "#{@thm_primary}"
set -g mode-style "fg=#{@thm_primary} bg=#{@thm_selection} bold"
